### ISSUE TITLE
Sometimes blocked at Enqueue?

### ISSUE THREAD

**Issue by xzzh999** [enriquebris/goconcurrentqueue#27]
FixedFIFO sometimes blocked at the **Enqueue** function when the queue is empty, and i use 
**context.WithTimeout** and **DequeueOrWaitForNextElementContext** to deque item in another routine:
```
// Enqueue enqueues an element. Returns error if queue is locked or it is at full capacity.
func (st *FixedFIFO) Enqueue(value interface{}) error {
	if st.IsLocked() {
		return NewQueueError(QueueErrorCodeLockedQueue, "The queue is locked")
	}

	// check if there is a listener waiting for the next element (this element)
	select {
	case listener := <-st.waitForNextElementChan:

               //
---->          //  *** blocked here!!!
               //
		// send the element through the listener's channel instead of enqueue it
		listener <- value

	default:
		// enqueue the element following the "normal way"
		select {
		case st.queue <- value:
		default:
			return NewQueueError(QueueErrorCodeFullCapacity, "FixedFIFO queue is at full capacity")
		}
	}
```
deque (not blocking):
```
ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	qItem, err := tp.ReqCacheQueue.DequeueOrWaitForNextElementContext(ctx)
	if err != nil {
		if err == context.DeadlineExceeded {
			return
		}
		qErr, ok := err.(*goconcurrentqueue.QueueError)
		if ok && qErr != nil {
			if qErr.Code() == goconcurrentqueue.QueueErrorCodeEmptyQueue {
				time.Sleep(100 * time.Millisecond)
				return
			}
		}
		log.Error("process task err: ", err)
		return
	}
```

**Comment by xzzh999** [comment]
and if i use **DequeueOrWaitForNextElement** instead of **DequeueOrWaitForNextElementContext**, it's ok

**Comment by enriquebris** [comment]
Hi @xzzh999, I'll check the issue you reported asap.

**Comment by xzzh999** [comment]
@enriquebris ok, 3Q
And for now i make my own timeout outside, it works fine.

**Comment by enriquebris** [comment]
@xzzh999,

Root cause: **FixedFifo.Enqueue** gets blocked if **DequeueOrWaitForNextElementContext()** was invoked before (and it keeps waiting for a new enqueued item) and the given context expires while Enqueue is doing its job.

Fix: https://github.com/enriquebris/goconcurrentqueue/pull/28 (already merged against master)

Please let me know if this fixes your code.

Thanks,
Enrique

**Comment by xzzh999** [comment]
@enriquebris 
The master branch is testing fine, thank you for u good work.
