### ISSUE TITLE
 FixedFIFO use DequeueOrWaitForNextElement will can stuck forever

### ISSUE THREAD

**Issue by testwill** [enriquebris/goconcurrentqueue#34]
If I use 5 producers and one consumer, when I use DequeueOrWaitForNextElement to dequeue, the consumer will be stuck in ctx.Done() (cannot consume data). Then the producer will fill up the queue and keep reporting FixedFIFO queue is at full capacity. At this time waitForNextElementChan is empty
code:
`package main

import (
	"fmt"
	"math/rand"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/enriquebris/goconcurrentqueue"
)

type AnyStruct struct {
	Field1 string
	Field2 int
}

var (
	queue *goconcurrentqueue.FixedFIFO
)

func main() {

	queue = goconcurrentqueue.NewFixedFIFO(4096)
	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
	done := make(chan bool, 1)
	// will output: 3
	fmt.Printf("queue's length: %v\n", queue.GetCap())

	for i := 0; i < 5; i++ {
		go product()
	}

	go consume()

	go func() {
		sig := <-sigs
		fmt.Println()
		fmt.Println(sig)
		done <- true
	}()

	fmt.Println("awaiting signal")
	<-done
	fmt.Println("exiting")
}

func product() {
	rand.Seed(time.Now().UnixNano())

	for {
		i := rand.Intn(1000000000)
		val := &AnyStruct{Field1: fmt.Sprintf("hello world %d", i), Field2: i}
		err := queue.Enqueue(val)
		if err != nil {
			//	fmt.Println(err)
		}
		time.Sleep(time.Microsecond * 100)
	}
}

func consume() {
	for {
		//ctx, cancel := context.WithTimeout(context.Background(), time.Duration(time.Millisecond*80))
		//defer cancel()
		//val, err  :=queue.DequeueOrWaitForNextElementContext(ctx)
		val, err := queue.DequeueOrWaitForNextElement()
		if err == nil {
			ele := val.(*AnyStruct)
			fmt.Println(ele.Field1, ", ", ele.Field2)
		} else {
			fmt.Println(err)
			time.Sleep(time.Second)
		}
	}

}
`

**Comment by enriquebris** [comment]
Hi @testwill!

I'm going to run your code ASAP in order to dissect the issue you are dealing with. I'll let you know as soon as I get further details.

Enrique

**Comment by testwill** [comment]
thanks

**Comment by enriquebris** [comment]
Hi @testwill ,

The issue was fixed in the latest version: [v0.7.0](https://github.com/enriquebris/goconcurrentqueue/releases/tag/v0.7.0)

Please try again and let me know if you get any other issue.

Good catch!
Thank you
Enrique

**Comment by testwill** [comment]
I tested it, and there is no problem so far.Thank you
